// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA520BDV-7fw_XpcQy6fHYSbISvus9NSlc',
    appId: '1:697550549075:web:6f5490c6556258835016a6',
    messagingSenderId: '697550549075',
    projectId: 'hana-ouerghemmi',
    authDomain: 'hana-ouerghemmi.firebaseapp.com',
    storageBucket: 'hana-ouerghemmi.appspot.com',
    measurementId: 'G-EZJWETY4G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYZttyDhEh_0tRMtbCxZZod-DCSTvPCtQ',
    appId: '1:697550549075:android:316d4d4d1a6ece225016a6',
    messagingSenderId: '697550549075',
    projectId: 'hana-ouerghemmi',
    storageBucket: 'hana-ouerghemmi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHa5-6Rtjg4E8yt_kp4C3AqliLPd_Gv0Y',
    appId: '1:697550549075:ios:cbab5312c4ab33b75016a6',
    messagingSenderId: '697550549075',
    projectId: 'hana-ouerghemmi',
    storageBucket: 'hana-ouerghemmi.appspot.com',
    iosBundleId: 'com.example.hanaportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHa5-6Rtjg4E8yt_kp4C3AqliLPd_Gv0Y',
    appId: '1:697550549075:ios:c03ab955bce770345016a6',
    messagingSenderId: '697550549075',
    projectId: 'hana-ouerghemmi',
    storageBucket: 'hana-ouerghemmi.appspot.com',
    iosBundleId: 'com.example.hanaportfolio.RunnerTests',
  );
}
